### ISSUE TITLE
Distance Matrix for multiple TS

### ISSUE THREAD

**Issue by ghost** [garrettwrong/cuTWED#25]
Thank you for providing this project.

Is there an efficient way to calculate a distance matrix for multiple time-series?
This is a very useful feature for time-series analysis and is for example implemented [here](https://dtaidistance.readthedocs.io/en/latest/usage/dtw.html) for dynamic time warping.

**Comment by garrettwrong** [comment]
Sort of yes.  If the time series have the same number of samples there is a batch method that will compute them in bulk, returning an upper or lower triangle of pair wise distances.  A user reported a factor of three speedup for their problem, but in my personal experience it was only a little faster than computing the same pairs yourself (in a loop). It will really depend on the problem sizes and hardware.

**Comment by garrettwrong** [comment]
This would be the _batch methods...
