### ISSUE TITLE
improvement: twed_malloc_dev (and twed_free_dev) A and B data separately

### ISSUE THREAD

**Issue by mw66** [garrettwrong/cuTWED#28]
Hi,

https://github.com/garrettwrong/cuTWED/blob/master/src/cuTWED_core.h#L384

Right now, twed_malloc_dev and twed_free_dev A and B data together in one function call.

Suppose, I have 3 set of data [A, B, C], and want to calc twed(A, B), and twed(A, C). For the maximal efficiency, I'd like to load A to GPU only once, and call

```
// init
twed_malloc_dev(A);

// run the following 2 blocks in parallel:
{B = generate("b"); twed_malloc_dev(B); twed_dev(A_dev, B_dev); twed_free_dev(B_dev);}
{C = generate("c"); twed_malloc_dev(C); twed_dev(A_dev, C_dev); twed_free_dev(C_dev);}

// all_thread_join();

// finally
twed_free_dev(A);
```

i.e the A_dev data is shared, and malloc & free-ed only once.

This require twed_malloc_dev (and twed_free_dev) A and B data separately. Do you think it will work?

A related question: is twed_dev thread (-- it's not quite threading, but just parallel) safe? i.e we can run the above 2 blocks of code in parallel without causing any trouble?

Thanks.

**Comment by garrettwrong** [comment]
Hi, you are actually asking several different usage questions... (also your example code has B double free'd so, no, that will not work, but I'll just assume that was a typo for C).

First, I do not believe the original signal and timestamp arrays are overwritten at any point by `twed_dev`. Next time I do an update I will make that more clear, thanks.

Second, by inspection `twed_malloc_dev` calls are just utility helper wrappers over CUDA malloc and copy. You do not need to use my wrappers if you prefer to do something different.  `twed_dev` only expects the arrays exist on the GPU with the expected size and contents at time of the call. How you get there is not my business :). Any questions relating to thread safety etc of common CUDA Runtime calls should be had from their official documentation. This code is very much intentionally agnostic...
 
###

There are two things going on with your code. One is an attempt (by threading) at concurrent overlap of memory transfer/computation and the other is loading of the GPU.  You will not gain much above machine noise overlapping the memory transfer of this specific problem, (I have measured this);  I will ignore that and suggest you do the same.  If you must, you should probably be looking  at CUDA Async alloc/transfer/stream calls for your application instead... and managing that yourself...

If you are trying to overlap some generation process with TWED calls you may still do that, but not with the code you suggested, and it is not something in scope as a github issue... It just isn't an issue with my software or the use of it... and really isn't an issue of improving this software as much as changing/writing the calling code.

So then, if I now assume we are just trying to load the GPU more:

When you have several time series and want to launch more kernels, there is a `_batch` method.  This computes a batch of multiple timeseries simultaneously. In your case if B and C are available simultaneously you may use this to the same effect as your code. Likely it is more efficient...

To do so you can just make a larger array BB that is the concatenation of B and C. Similarly for the timestamps.  That would imply the var nBB=2 (ie there are two time series).  Currently this expects dense (non ragged) arrays so you may have to pad your time series if they are not equal length.

If you actually require all pairs (A,B) (A,C) (B,C) , again I would recommend the batch implementation and compute in mode  `tri=-1`. For this you would concatenate A, B, C into a new array AA and nAA=3. You would pass that also for BB and nBB. The code will return the lower triangular matrix of all pairs.  There are unit tests which contain the syntax of the batch calls. It really depends on the problems size whether this will yield speedups.

I have had another request to add some more documentation for batching, and will do so at some point.

**Comment by mw66** [comment]
Thanks for the detailed reply.

> Hi, you are actually asking several different usage questions... (also your example code has B double free'd so, no, that will not work, but I'll just assume that was a typo for C).
> 

Yes, it's a typo for C, I just fixed it.

> First, I do not believe the original signal and timestamp arrays are overwritten at any point by `twed_dev`. Next time I do an update I will make that more clear, thanks.

That's great, which means the A_dev, and TA_dev once uploaded onto GPU, these input data are read only, hence safe to be shared by different calls. (I vaguely remember that CUDA has some flag to tell the nvcc compiler that those memory are read only? I need to check the manual.) 

> Second, by inspection `twed_malloc_dev` calls are just utility helper wrappers over CUDA malloc and copy. You do not need to use my wrappers if you prefer to do something different.
> 

Sure.

> If you are trying to overlap some generation process with TWED calls you may still do that

Yes, that's my intention, I also edit the original post to add `B = generate("b");` in to the parallel blocks to make it clear.

The generation process is time consuming, and actually in my application, there are actually thousands of `[B, C, D, ...]`, all to be calc `twed()` with the same `A`. That's why I want to avoid uploading `A` thousands of times always with these `[B, C, D, ...]` each time in pairs.

I just want to make sure uploading `A` once, and then `{uploading [B, C, D, ...]; and call twed()}` separately in diff thread (on different CPU cores)  are safe to do so.

> If you actually require all pairs (A,B) (A,C) (B,C) , again I would recommend the batch implementation and compute in mode `tri=-1`. For this you would concatenate A, B, C into a new array AA and nAA=3. You would pass that also for BB and nBB. The code will return the lower triangular matrix of all pairs. There are unit tests which contain the syntax of the batch calls. It really depends on the problems size whether this will yield speedups.

Thanks for this info, it's good to know. One more question in this part: you said

> "You would pass that also for BB and nBB."

Does it means, we can pass the the same AA_dev twice as this:
```
  int twed_batch_dev(AA_dev, nA, TAA_dev,
                     AA_dev, nA, TAA_dev, ...);
```

which meas the input "original signal and timestamp arrays are" truly read-only, so the same AA_dev and TAA_dev can be passed into the function, as both A and B.

Thanks.

**Comment by garrettwrong** [comment]
Hi yes, the inputs should be read only.  I think I only enforced that the pointer remained `const`. I did not also enforce `const` on the values, but that was probably just oversight (or could have been to keep warnings quiet, I don't remember..).

Yes, you may pass the same array twice for the batch mode if you want all pairs. It is a little clunky, but avoids having too many special case interfaces. The documentation for the few I do have is already lacking :).

I hope your project works out well.

Garrett
